const NavigationScreens = {
  HooksUseState: 'HooksUseState',
  HookUseEffects: 'HookUseEffects',
  HooksUseCallback: 'HooksUseCallback',
  HooksUseCallContext: 'HooksUseCallContext',
  HooksUseMemo: 'HooksUseMemo',
  HooksUseRef: 'HooksUseRef',
  HooksUseId: 'HooksUseId',
  HooksUseDebug: 'HooksUseDebug',
  AdvancedPkgFormik: 'AdvancedPkgFormik',
  AdvancedPkgWebView: 'AdvancedPkgWebView',
  AdvancedPkgDatePicker: 'AdvancedPkgDatePicker',
  HookUseFormik: 'HookUseFormik',
  AdvancedPkgDocumentPicker: 'AdvancedPkgDocumentPicker',
  AdvancedPkgImagePicker: 'AdvancedPkgImagePicker',
  AdvancedPkgCrousal: 'AdvancedPkgCarousal',
  AdvancedPkgActionSheet: 'AdvancedPkgActionSheet',
  AdvancedPkgLinearGradiant: 'AdvancedPkgLinearGradiant',
  AdvancedPkgLottieAnimation: 'AdvancedPkgLottieAnimation',
  AdvancedPkgLocalization: 'AdvancedPkgLocalization',
  AdvancedPkgMap: 'AdvancedPkgMap',
  AdvancedPkgCamera: 'AdvancedPkgCamera',
  ApiToDo: 'Fetch Method',
  ApiToDoUsingAxios: 'Axios Method',
  ApiToDoAuthentication: 'Authentication API',
  TodoReduxCore: 'Redux Core',
  TodoReduxSlice: 'Redux Slice',
  TodoAppTask: 'Ecommerce',
  TodoAppPersonalDetails: 'Person Details',
};

export default NavigationScreens;
